WebApplicationStudenciMVC/Models/Prowadzacy.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStudenciMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prowadzacy
    {
        public int ID_prowadzacego { get; set; }
        public string P_Imie { get; set; }
        public string P_Nazwisko { get; set; }
        public string P_Stopien_naukowy { get; set; }
        public string P_Stanowisko { get; set; }
        public string P_Adres { get; set; }
    }
}

WebApplicationStudenciMVC/Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationStudenciMVC.Models;

namespace WebApplicationStudenciMVC.Controllers
{
    public class LoginsController : Controller
    {
        private StudenciWebAppEntities db = new StudenciWebAppEntities();

        // GET: Logins
        public ActionResult Index()
        {
            return View(db.Login.ToList());
        }

        // GET: Logins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Login.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // GET: Logins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Logins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Login login)
        {
            if (ModelState.IsValid)
            {
                string uName = login.Username;
                string pass = login.Password;

                using (StudenciWebAppEntities db = new StudenciWebAppEntities())
                {
                    try
                    {
                        var result = db.Login.First(c => c.Username == uName && c.Password == pass);
                        if (result.Role == "admin")
                        {
                            //return RedirectToAction("Index", new
                            //{
                            //    ID = model.ID,
                            //    projectName = model.ProjectName
                            //});
                            return RedirectToAction("Index");

                        }
                        else if (result.Role == "student")
                        {
                            Response.Write("hello student!");
                            return RedirectToAction("Index", "StudencisPage");


                        }
                        else if (result.Role == "prowadzacy")
                        {
                            Response.Write("hello prowadzacy!");
                            return RedirectToAction("Index", "ProwadzacyPage");
                        }
                    }
                    catch (Exception)
                    {
                        return RedirectToAction("Create");

                    }

                };

            }

            return View(login);
        }

        // GET: Logins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Login.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: Logins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_login,Username,Password,Role")] Login login)
        {
            if (ModelState.IsValid)
            {
                db.Entry(login).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(login);
        }

        // GET: Logins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Login.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: Logins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Login login = db.Login.Find(id);
            db.Login.Remove(login);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationStudenciMVC/Controllers/ProwadzaciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationStudenciMVC.Models;

namespace WebApplicationStudenciMVC.Controllers
{
    public class ProwadzaciesController : Controller
    {
        private StudenciWebAppEntities db = new StudenciWebAppEntities();

        // GET: Prowadzacies
        public ActionResult Index()
        {
            return View(db.Prowadzacy.ToList());
        }

        // GET: Prowadzacies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prowadzacy prowadzacy = db.Prowadzacy.Find(id);
            if (prowadzacy == null)
            {
                return HttpNotFound();
            }
            return View(prowadzacy);
        }

        // GET: Prowadzacies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Prowadzacies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_prowadzacego,P_Imie,P_Nazwisko,P_Stopien_naukowy,P_Stanowisko,P_Adres")] Prowadzacy prowadzacy)
        {
            if (ModelState.IsValid)
            {
                db.Prowadzacy.Add(prowadzacy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(prowadzacy);
        }

        // GET: Prowadzacies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prowadzacy prowadzacy = db.Prowadzacy.Find(id);
            if (prowadzacy == null)
            {
                return HttpNotFound();
            }
            return View(prowadzacy);
        }

        // POST: Prowadzacies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_prowadzacego,P_Imie,P_Nazwisko,P_Stopien_naukowy,P_Stanowisko,P_Adres")] Prowadzacy prowadzacy)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prowadzacy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(prowadzacy);
        }

        // GET: Prowadzacies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prowadzacy prowadzacy = db.Prowadzacy.Find(id);
            if (prowadzacy == null)
            {
                return HttpNotFound();
            }
            return View(prowadzacy);
        }

        // POST: Prowadzacies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prowadzacy prowadzacy = db.Prowadzacy.Find(id);
            db.Prowadzacy.Remove(prowadzacy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationStudenciMVC/Views/Prowadzacies/Create.cshtml
@model WebApplicationStudenciMVC.Models.Prowadzacy

@{
    ViewBag.Title = "Dodaj";
}

<h2>Nowy</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Prowadzacy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.P_Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Stopien_naukowy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Stopien_naukowy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Stopien_naukowy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Stanowisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Stanowisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Stanowisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Adres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Adres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Adres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Nowy" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Wróć do listy", "Index") |
        @Html.ActionLink("Powrót do menu", "Index", "Logins")
    </div>

WebApplicationStudenciMVC/Views/Prowadzacies/Delete.cshtml
@model WebApplicationStudenciMVC.Models.Prowadzacy

@{
    ViewBag.Title = "Usuń";
}

<h2>Usuń</h2>

<h3>Czy jesteś pewien że chcesz to usunąć?</h3>
<div>
    <h4>Prowadzacy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.P_Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Stopien_naukowy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Stopien_naukowy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Stanowisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Stanowisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Adres)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Usuń" class="btn btn-default" /> |
        @Html.ActionLink("Wróć do listy", "Index") |
        @Html.ActionLink("Powrót do menu", "Index", "Logins")
    </div>
    }
</div>

WebApplicationStudenciMVC/Views/Prowadzacies/Details.cshtml
@model WebApplicationStudenciMVC.Models.Prowadzacy

@{
    ViewBag.Title = "Detale";
}

<h2>Details</h2>

<div>
    <h4>Prowadzacy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.P_Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Stopien_naukowy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Stopien_naukowy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Stanowisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Stanowisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P_Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_Adres)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.ID_prowadzacego }) |
    @Html.ActionLink("Wróc do listy", "Index") |
    @Html.ActionLink("Powrót do menu", "Index", "Logins")
</p>

WebApplicationStudenciMVC/Views/Prowadzacies/Edit.cshtml
@model WebApplicationStudenciMVC.Models.Prowadzacy

@{
    ViewBag.Title = "Edytuj";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Prowadzacy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_prowadzacego)

        <div class="form-group">
            @Html.LabelFor(model => model.P_Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Stopien_naukowy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Stopien_naukowy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Stopien_naukowy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Stanowisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Stanowisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Stanowisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Adres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Adres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Adres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Wróć do listy", "Index") |
        @Html.ActionLink("Powrót do menu", "Index", "Logins")
    </div>

WebApplicationStudenciMVC/Views/Prowadzacies/Index.cshtml
@model IEnumerable<WebApplicationStudenciMVC.Models.Prowadzacy>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Dodaj", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.P_Imie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.P_Nazwisko)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.P_Stopien_naukowy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.P_Stanowisko)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.P_Adres)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.P_Imie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P_Nazwisko)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P_Stopien_naukowy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P_Stanowisko)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.P_Adres)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.ID_prowadzacego }) |
                @Html.ActionLink("Detale", "Details", new { id = item.ID_prowadzacego }) |
                @Html.ActionLink("Usuń", "Delete", new { id = item.ID_prowadzacego })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Powrót do menu", "Index", "Logins") 