WebApplicationStudenciMVC/Controllers/ProjektiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationStudenciMVC.Models;

namespace WebApplicationStudenciMVC.Controllers
{
    public class ProjektiesController : Controller
    {
        private StudenciWebAppEntities db = new StudenciWebAppEntities();

        // GET: Projekties
        public ActionResult Index()
        {
            return View(db.Projekty.ToList());
        }

        // GET: Projekties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projekty projekty = db.Projekty.Find(id);
            if (projekty == null)
            {
                return HttpNotFound();
            }
            return View(projekty);
        }

        // GET: Projekties/Create
        public ActionResult Create()
        {
            PopulateProjektyDropDownList();
            return View();
        }

        // POST: Projekties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Projektu,ID_przedmiotu,Nazwa_projektu,Data_projektu")] Projekty projekty)
        {
            if (ModelState.IsValid)
            {
                db.Projekty.Add(projekty);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateProjektyDropDownList(projekty.ID_przedmiotu);
            return View(projekty);
        }

        // GET: Projekties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projekty projekty = db.Projekty.Find(id);
            if (projekty == null)
            {
                return HttpNotFound();
            }
            return View(projekty);
        }

        // POST: Projekties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Projektu,ID_przedmiotu,Nazwa_projektu,Data_projektu")] Projekty projekty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projekty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projekty);
        }

        // GET: Projekties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projekty projekty = db.Projekty.Find(id);
            if (projekty == null)
            {
                return HttpNotFound();
            }
            return View(projekty);
        }

        // POST: Projekties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Projekty projekty = db.Projekty.Find(id);
            db.Projekty.Remove(projekty);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private void PopulateProjektyDropDownList(object selectedPrzedmiot = null)
        {
            var projektyQuery = from d in db.Przedmioty
                                     orderby d.ID_przedmiotu
                                     select d;
            ViewBag.ID_przedmiotu = new SelectList(projektyQuery, "ID_przedmiotu", "Nazwa_przedmiotu", selectedPrzedmiot);
        }
    }
}

WebApplicationStudenciMVC/Controllers/PrzedmiotiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationStudenciMVC.Models;

namespace WebApplicationStudenciMVC.Controllers
{
    public class PrzedmiotiesController : Controller
    {
        private StudenciWebAppEntities db = new StudenciWebAppEntities();

        // GET: Przedmioties
        public ActionResult Index()
        {
            return View(db.Przedmioty.ToList());
        }

        // GET: Przedmioties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            if (przedmioty == null)
            {
                return HttpNotFound();
            }
            return View(przedmioty);
        }

        // GET: Przedmioties/Create
        public ActionResult Create()
        {
            PopulateProwadzacyDropDownList();
            PopulateSpecjalizacjaDropDownList();
            return View();
        }

        // POST: Przedmioties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_przedmiotu,ID_prowadzacego,ID_Specjalizacji,Nazwa_przedmiotu,ECTS")] Przedmioty przedmioty)
        {
            if (ModelState.IsValid)
            {
                db.Przedmioty.Add(przedmioty);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateProwadzacyDropDownList(przedmioty.ID_prowadzacego);
            PopulateSpecjalizacjaDropDownList(przedmioty.ID_Specjalizacji);
            return View(przedmioty);
        }

        // GET: Przedmioties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            if (przedmioty == null)
            {
                return HttpNotFound();
            }
            return View(przedmioty);
        }

        // POST: Przedmioties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_przedmiotu,ID_prowadzacego,ID_Specjalizacji,Nazwa_przedmiotu,ECTS")] Przedmioty przedmioty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(przedmioty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(przedmioty);
        }

        // GET: Przedmioties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            if (przedmioty == null)
            {
                return HttpNotFound();
            }
            return View(przedmioty);
        }

        // POST: Przedmioties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            db.Przedmioty.Remove(przedmioty);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private void PopulateProwadzacyDropDownList(object selectedProwadzacy = null)
        {
            var prowadzacyQuery = from d in db.Prowadzacy
                                     orderby d.ID_prowadzacego
                                     select d;
            ViewBag.ID_prowadzacego = new SelectList(prowadzacyQuery, "ID_prowadzacego", "P_Nazwisko", selectedProwadzacy);
        }
        private void PopulateSpecjalizacjaDropDownList(object selectedSpecjalizacja = null)
        {
            var specjalizacjaQuery = from d in db.Specjalizacja
                                  orderby d.ID_Specjalizacji
                                  select d;
            ViewBag.ID_Specjalizacji = new SelectList(specjalizacjaQuery, "ID_Specjalizacji", "Nazwa_specjalizacji", selectedSpecjalizacja);
        }
    }
}

WebApplicationStudenciMVC/Controllers/ZapisanisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationStudenciMVC.Models;

namespace WebApplicationStudenciMVC.Controllers
{
    public class ZapisanisController : Controller
    {
        private StudenciWebAppEntities db = new StudenciWebAppEntities();

        // GET: Zapisanis
        public ActionResult Index()
        {
            return View(db.Zapisani.ToList());
        }

        // GET: Zapisanis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapisani zapisani = db.Zapisani.Find(id);
            if (zapisani == null)
            {
                return HttpNotFound();
            }
            return View(zapisani);
        }

        // GET: Zapisanis/Create
        public ActionResult Create()
        {
            PopulateZapisStudentProjDropDownList();
            PopulateZapisProjektProjDropDownList();
            return View();
        }

        // POST: Zapisanis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Zapisani,Z_Student,Z_Projekt,Z_Termin")] Zapisani zapisani)
        {
            if (ModelState.IsValid)
            {
                db.Zapisani.Add(zapisani);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateZapisStudentProjDropDownList(zapisani.Z_Student);
            PopulateZapisProjektProjDropDownList(zapisani.Z_Projekt);
            return View(zapisani);
        }

        // GET: Zapisanis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapisani zapisani = db.Zapisani.Find(id);
            if (zapisani == null)
            {
                return HttpNotFound();
            }
            return View(zapisani);
        }

        // POST: Zapisanis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Zapisani,Z_Student,Z_Projekt,Z_Termin")] Zapisani zapisani)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zapisani).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(zapisani);
        }

        // GET: Zapisanis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zapisani zapisani = db.Zapisani.Find(id);
            if (zapisani == null)
            {
                return HttpNotFound();
            }
            return View(zapisani);
        }

        // POST: Zapisanis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zapisani zapisani = db.Zapisani.Find(id);
            db.Zapisani.Remove(zapisani);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private void PopulateZapisStudentProjDropDownList(object selectedOczekujacy = null)
        {
            var oczekujacyDoZapisuStudentQuery = from d in db.Oczekujacy
                                     orderby d.O_indeks
                                     select d;
            ViewBag.Z_Student = new SelectList(oczekujacyDoZapisuStudentQuery, "O_indeks", "O_indeks", selectedOczekujacy);
        }

        private void PopulateZapisProjektProjDropDownList(object selectedOczekujacy = null)
        {
            var oczekujacyDoZapisuProjektQuery = from d in db.Oczekujacy
                                                 orderby d.O_projekt
                                                 select d;
            ViewBag.Z_Projekt = new SelectList(oczekujacyDoZapisuProjektQuery, "O_projekt", "O_projekt", selectedOczekujacy);
        }
    }
}

WebApplicationStudenciMVC/Views/ProwadzacyPage/Create.cshtml
@model WebApplicationStudenciMVC.Models.Login

@{
    ViewBag.Title = "Create";
}

<h2>Nowy</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id_login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

WebApplicationStudenciMVC/Views/ProwadzacyPage/Delete.cshtml
@model WebApplicationStudenciMVC.Models.Login

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń</h2>

<h3>Jesteś pewien że chcesz to usunąć?</h3>
<div>
    <h4>Login</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

WebApplicationStudenciMVC/Views/ProwadzacyPage/Details.cshtml
@model WebApplicationStudenciMVC.Models.Login

@{
    ViewBag.Title = "Details";
}

<h2>Detale</h2>

<div>
    <h4>Login</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id_login }) |
    @Html.ActionLink("Wróć do listy", "Index")
</p>

WebApplicationStudenciMVC/Views/ProwadzacyPage/Edit.cshtml
@model WebApplicationStudenciMVC.Models.Login

@{
    ViewBag.Title = "Edit";
}

<h2>Edytuj</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_login)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

WebApplicationStudenciMVC/Views/ProwadzacyPage/Index.cshtml
@model IEnumerable<WebApplicationStudenciMVC.Models.Login>

@{
    ViewBag.Title = "Main";
}

<h1>Witaj prowadzący!</h1>
<h2>Co chcesz dziś zrobić?</h2>

<h3>Zarządzaj przedmiotami</h3>
@Html.ActionLink("Zarządzaj przedmiotami", "Index", "Przedmioties")
<h3>Zarządzaj projektami</h3>
@Html.ActionLink("Zarządzaj projektami", "Index", "Projekties")
<h3>Zarządzaj ocenami z projektów</h3>
@Html.ActionLink("Zarządzaj ocenami", "Index", "Oceny_projekty")
<h3>Zarządzaj ocenami z przedmiotów</h3>
@Html.ActionLink("Zarządzaj ocenami", "Index", "Oceny_przedmioty")
<h3>Sprawdź zgłoszenia do projektów</h3>
@Html.ActionLink("Zgłoszenia do projektów", "Index", "Zapisanis")