WebApplicationStudenciMVC/Controllers/OczekujaciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationStudenciMVC.Models;

namespace WebApplicationStudenciMVC.Controllers
{
    public class OczekujaciesController : Controller
    {
        private StudenciWebAppEntities db = new StudenciWebAppEntities();

        // GET: Oczekujacies
        public ActionResult Index()
        {
            return View(db.Oczekujacy.ToList());
            //return RedirectToAction("Index","StudencisPage");
        }

        // GET: Oczekujacies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oczekujacy oczekujacy = db.Oczekujacy.Find(id);
            if (oczekujacy == null)
            {
                return HttpNotFound();
            }
            return View(oczekujacy);
        }

        // GET: Oczekujacies/Create
        public ActionResult Create()
        {
            PopulateStudentDropDownList();
            PopulateProjektyDropDownList();
            return View();
        }

        // POST: Oczekujacies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "O_ID,O_indeks,O_projekt")] Oczekujacy oczekujacy)
        {
            if (ModelState.IsValid)
            {
                db.Oczekujacy.Add(oczekujacy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateStudentDropDownList(oczekujacy.O_indeks);
            PopulateProjektyDropDownList(oczekujacy.O_projekt);
            return View(oczekujacy);
        }

        // GET: Oczekujacies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oczekujacy oczekujacy = db.Oczekujacy.Find(id);
            if (oczekujacy == null)
            {
                return HttpNotFound();
            }
            return View(oczekujacy);
        }

        // POST: Oczekujacies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "O_ID,O_indeks,O_projekt")] Oczekujacy oczekujacy)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oczekujacy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(oczekujacy);
        }

        // GET: Oczekujacies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oczekujacy oczekujacy = db.Oczekujacy.Find(id);
            if (oczekujacy == null)
            {
                return HttpNotFound();
            }
            return View(oczekujacy);
        }

        // POST: Oczekujacies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oczekujacy oczekujacy = db.Oczekujacy.Find(id);
            db.Oczekujacy.Remove(oczekujacy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private void PopulateStudentDropDownList(object selectedStudent = null)
        {
            var studenciQuery = from d in db.Studenci
                                orderby d.ST_Nr_indeksu
                                select d;
            ViewBag.O_indeks = new SelectList(studenciQuery, "ST_Nr_indeksu", "ST_Nr_indeksu", selectedStudent);
        }
        private void PopulateProjektyDropDownList(object selectedPrzedmiot = null)
        {
            var projektyQuery = from d in db.Projekty
                                orderby d.Nazwa_projektu
                                select d;
            ViewBag.O_projekt = new SelectList(projektyQuery, "Nazwa_projektu", "Nazwa_projektu", selectedPrzedmiot);
        }
    }
}

WebApplicationStudenciMVC/Controllers/StudencisPageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationStudenciMVC.Models;

namespace WebApplicationStudenciMVC.Controllers
{
    public class StudencisPageController : Controller
    {
        private StudenciWebAppEntities db = new StudenciWebAppEntities();

        // GET: StudencisPage
        public ActionResult Index()
        {
            return View(db.Studenci.ToList());
        }

        // GET: StudencisPage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studenci studenci = db.Studenci.Find(id);
            if (studenci == null)
            {
                return HttpNotFound();
            }
            return View(studenci);
        }

        // GET: StudencisPage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudencisPage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Studenta,ID_Specjalizacji,ST_Imie,ST_Nazwisko,ST_Adres,ST_Nr_indeksu,ST_Data_urodzenia")] Studenci studenci)
        {
            if (ModelState.IsValid)
            {
                db.Studenci.Add(studenci);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studenci);
        }

        // GET: StudencisPage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studenci studenci = db.Studenci.Find(id);
            if (studenci == null)
            {
                return HttpNotFound();
            }
            return View(studenci);
        }

        // POST: StudencisPage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Studenta,ID_Specjalizacji,ST_Imie,ST_Nazwisko,ST_Adres,ST_Nr_indeksu,ST_Data_urodzenia")] Studenci studenci)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studenci).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studenci);
        }

        // GET: StudencisPage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studenci studenci = db.Studenci.Find(id);
            if (studenci == null)
            {
                return HttpNotFound();
            }
            return View(studenci);
        }

        // POST: StudencisPage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Studenci studenci = db.Studenci.Find(id);
            db.Studenci.Remove(studenci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationStudenciMVC/Views/StudencisPage/Create.cshtml
@model WebApplicationStudenciMVC.Models.Studenci

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Studenci</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_Studenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Studenta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Studenta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Specjalizacji, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Specjalizacji, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Specjalizacji, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Adres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Adres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Adres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Nr_indeksu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Nr_indeksu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Nr_indeksu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Data_urodzenia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Data_urodzenia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Data_urodzenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Nowy" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplicationStudenciMVC/Views/StudencisPage/Delete.cshtml
@model WebApplicationStudenciMVC.Models.Studenci

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Studenci</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Specjalizacji)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Specjalizacji)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Nr_indeksu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Nr_indeksu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Data_urodzenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Data_urodzenia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplicationStudenciMVC/Views/StudencisPage/Details.cshtml
@model WebApplicationStudenciMVC.Models.Studenci

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Studenci</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Specjalizacji)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Specjalizacji)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Nr_indeksu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Nr_indeksu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ST_Data_urodzenia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ST_Data_urodzenia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Studenta }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplicationStudenciMVC/Views/StudencisPage/Edit.cshtml
@model WebApplicationStudenciMVC.Models.Studenci

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Studenci</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Studenta)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Specjalizacji, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Specjalizacji, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Specjalizacji, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Adres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Adres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Adres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Nr_indeksu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Nr_indeksu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Nr_indeksu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ST_Data_urodzenia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ST_Data_urodzenia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ST_Data_urodzenia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplicationStudenciMVC/Views/StudencisPage/Index.cshtml
@model IEnumerable<WebApplicationStudenciMVC.Models.Studenci>

@{
    ViewBag.Title = "Index";
}
<h1>Witaj student!</h1>
<h2>Co chcesz dziś zrobić?</h2>

<h3>Wpisz się na projekt</h3>
@Html.ActionLink("Wpisz się na projekt", "Create", "Oczekujacies")
<h3>Sprawdź oceny z projektów</h3>
@Html.ActionLink("Sprawdź oceny z projektów", "Index", "Oceny_projekty")
<h3>Sprawdź oceny z przedmiotów</h3>
@Html.ActionLink("Sprawdź oceny z przedmiotów", "Index", "Oceny_przedmioty")